export { default as Home } from './Home/Home.tsx'
export { default as Learn } from './Learn/Learn'
export { default as Gallery } from './Gallery/Gallery.tsx'
export { default as Contact } from './Contact/Contact.tsx'
export { default as NotFound } from './NotFound/NotFound.tsx'
export { default as Register } from './SignUp/SignUp.tsx'